//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HESProgram.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Analysis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Analysis()
        {
            this.LabReports = new HashSet<LabReport>();
            this.addAnalysis = new HashSet<addAnalysi>();
            this.SampleResults = new HashSet<SampleResult>();
        }
    
        public int AnalysisId { get; set; }
        public string AirContaminant { get; set; }
        public string Attachment { get; set; }
        public string Method { get; set; }
        public Nullable<decimal> PEL { get; set; }
        public Nullable<decimal> STEL { get; set; }
        public Nullable<decimal> CeilingLimit { get; set; }
        public Nullable<decimal> ActionLevel { get; set; }
        public Nullable<decimal> REL { get; set; }
        public Nullable<decimal> TLV { get; set; }
        public Nullable<decimal> TLVC { get; set; }
        public Nullable<decimal> TLVST { get; set; }
        public Nullable<decimal> RELC { get; set; }
        public Nullable<decimal> RELST { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LabReport> LabReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<addAnalysi> addAnalysis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SampleResult> SampleResults { get; set; }
    }
}
