//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HESProgram.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabReport
    {
        public int LabReportId { get; set; }
        public int ReportNumber { get; set; }
        public System.DateTime ReportDate { get; set; }
        public string ReportAttachment { get; set; }
        public Nullable<int> sampleId { get; set; }
        public Nullable<int> AnalysisId { get; set; }
    
        public virtual Analysis Analysis { get; set; }
    }
}
