//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HESProgram.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MineTask
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MineTask()
        {
            this.Samples = new HashSet<Sample>();
        }
    
        public int taskId { get; set; }
        public string taskDescription { get; set; }
        public string Respirator { get; set; }
        public string MedicalMonitoring { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sample> Samples { get; set; }
    }
}
