//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HESProgram.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IHEntities : DbContext
    {
        public IHEntities()
            : base("name=IHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Analysis> Analyses { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<LabReport> LabReports { get; set; }
        public virtual DbSet<MineTask> MineTasks { get; set; }
        public virtual DbSet<Weather> Weathers { get; set; }
        public virtual DbSet<Sample> Samples { get; set; }
        public virtual DbSet<addAnalysi> addAnalysis { get; set; }
        public virtual DbSet<SampleResult> SampleResults { get; set; }
    }
}
