//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HESProgram.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sample
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sample()
        {
            this.addAnalysis = new HashSet<addAnalysi>();
            this.SampleResults = new HashSet<SampleResult>();
        }
    
        public int SampleId { get; set; }
        public System.DateTime Date { get; set; }
        public decimal LPM { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public string FieldNotes { get; set; }
        public string FieldSampleId { get; set; }
        public string NotificationLetter { get; set; }
        public int EmployeeId { get; set; }
        public int taskId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual MineTask MineTask { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<addAnalysi> addAnalysis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SampleResult> SampleResults { get; set; }
    }
}
