//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HESProgram.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SampleResult
    {
        public int SampleResults { get; set; }
        public decimal Sample { get; set; }
        public decimal SampleWithAir { get; set; }
        public Nullable<decimal> EmployeeTWA { get; set; }
        public Nullable<decimal> BriefAndScala { get; set; }
        public decimal HoursWorked { get; set; }
        public int AnalysisId { get; set; }
        public int EmployeeId { get; set; }
        public int SampleId { get; set; }
    
        public virtual Analysis Analysis { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Sample Sample1 { get; set; }
    }
}
