//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HESProgram.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Weather
    {
        public int WeatherId { get; set; }
        public System.DateTime WeatherDate { get; set; }
        public string Wind { get; set; }
        public string WindDirection { get; set; }
        public string Temperature { get; set; }
        public decimal Humidity { get; set; }
        public decimal Precipitation { get; set; }
        public string WeatherType { get; set; }
    }
}
